#!/usr/bin/env python3

"""Linux-compatible UI translation script for Antigravity 2.0."""

import os

import sys

import re

import argparse





def to_single_quoted(value):

    escaped = value.replace("\\", "\\\\").replace("'", "\\'")

    return f"'{escaped}'"





def apply_safe_literal_replacement(content, original_literal, translated_literal):

    source_value = original_literal[1:-1]

    target_value = translated_literal[1:-1]

    before = content

    content = content.replace(repr(source_value).replace('"', "'"), to_single_quoted(target_value))

    content = content.replace(f'"{source_value}"', f'"{target_value}"')

    content = content.replace(to_single_quoted(source_value), to_single_quoted(target_value))

    content = content.replace(

        '"' + source_value.replace("\\", "\\\\").replace('"', '\\"') + '"',

        '"' + target_value.replace("\\", "\\\\").replace('"', '\\"') + '"',

    )

    return content, content != before





translations = {
    'label:"New Conversation"': 'label:"新建对话"',
    'label:"Create Project"': 'label:"创建项目"',
    'label:"Command Palette"': 'label:"命令面板"',
    'label:"Toggle Fullscreen"': 'label:"切换全屏"',
    'label:"Zoom In"': 'label:"放大"',
    'label:"Zoom Out"': 'label:"缩小"',
    'label:"Reset Zoom"': 'label:"重置缩放"',
    'label:"Toggle Developer Tools"': 'label:"开发者工具"',
    'label:"Minimize"': 'label:"最小化"',
    'label:"Maximize"': 'label:"最大化"',
    'label:"Close"': 'label:"关闭"',
    'label:"About"': 'label:"关于"',
    'label:"Check for Updates"': 'label:"检查更新"',
    'title:"File"': 'title:"文件"',
    'title:"View"': 'title:"视图"',
    'title:"Window"': 'title:"窗口"',
    '"New Conversation"': '"新建对话"',
    '"Scheduled Tasks"': '"计划任务"',
    '"Conversation History"': '"历史对话"',
    '"Projects"': '"项目"',
    '"No conversations yet"': '"暂无历史对话"',
    '"Settings"': '"设置"',
    '"Ask anything, @ to mention"': '"问任何问题，输入 @ 提及"',
    '", / for actions"': '"，输入 / 执行操作"',
    'aria-label:"Message input"': 'aria-label:"消息输入框"',
    '"Project General"': '"项目常规"',
    '"Project Folders"': '"项目文件夹"',
    '"Project Agent"': '"项目智能体"',
    '"Account"': '"账户"',
    '"Google Drive"': '"谷歌云端硬盘"',
    '"General"': '"通用"',
    '"Appearance"': '"外观"',
    '"Chat Settings"': '"对话设置"',
    '"Verbose agent chat"': '"详细智能体对话"',
    '"Display and preserve intermediate thinking steps"': '"显示并保留中间思考步骤"',
    '"Select light, dark, or inherit system settings."': '"选择浅色、深色或跟随系统设置。"',
    '"Light Theme"': '"浅色主题"',
    '"Dark Theme"': '"深色主题"',
    '"Preset"': '"预设"',
    '"Default Light"': '"默认浅色"',
    '"Default Dark"': '"默认深色"',
    '"Background"': '"背景"',
    '"Foreground"': '"前景"',
    '"Accent"': '"强调色"',
    '"Customizations"': '"自定义"',
    '"Notifications"': '"通知"',
    '"Editor"': '"编辑器"',
    '"Best of N"': '"Best of N"',
    '"Browser Settings"': '"浏览器设置"',
    '"App Settings"': '"应用设置"',
    '"Manage application settings."': '"管理应用设置。"',
    '"Configure settings for Best of N mode."': '"配置 Best of N 模式的相关设置。"',
    '"Best of N Settings"': '"Best of N 设置"',
    '"Shortcuts"': '"快捷键"',
    '"Provide Feedback"': '"提供反馈"',
    '"Notification Settings"': '"通知设置"',
    '"Open System Preferences"': '"打开系统设置"',
    '"Keyboard shortcuts for quick navigation and control."': '"用于快速导航和控制的键盘快捷键。"',
    '"RECOMMENDED"': '"推荐"',
    '"Open Conversation Picker"': '"打开对话选择器"',
    '"Open File Search"': '"打开文件搜索"',
    '"Focus Input"': '"聚焦输入框"',
    '"Go Back"': '"返回"',
    '"Go Forward"': '"前进"',
    '"File Picker"': '"文件选择器"',
    '"Select Previous Conversation"': '"选择上一个对话"',
    '"Select Next Conversation"': '"选择下一个对话"',
    '"CONVERSATION"': '"对话"',
    '"LAYOUT CONTROLS"': '"布局控制"',
    '"Toggle Model Selector"': '"切换模型选择器"',
    '"Toggle Voice Recording"': '"切换语音录制"',
    '"Find in Pane"': '"在面板中查找"',
    '"Toggle Sidebar"': '"切换侧边栏"',
    '"Toggle Auxiliary Pane"': '"切换辅助面板"',
    '"Enable Telemetry"': '"启用遥测"',
    '"Marketing Emails"': '"营销邮件"',
    '"Your Plan:"': '"当前套餐："',
    '"Upgrade"': '"升级"',
    '"Sign Out"': '"退出登录"',
    '"Email"': '"邮箱"',
    '"Terms of Service"': '"服务条款"',
    '"Conversations"': '"对话"',
    '"Not in Project"': '"未归属项目"',
    '"Workspaces"': '"工作区"',
    '"Show all"': '"显示全部"',
    '"Theme"': '"主题"',
    '"Keyboard Shortcuts"': '"快捷键"',
    '"No project selected or project management not available."': '"未选择项目，或项目管理不可用。"',
    '"Open Settings"': '"打开设置"',
    '"Open Keyboard Shortcuts"': '"打开快捷键列表"',
    '"No agents running"': '"当前没有运行中的智能体"',
    '"Folders"': '"文件夹"',
    '"Add Folder"': '"添加文件夹"',
    '"Agent Settings"': '"智能体设置"',
    '"Security Preset"': '"安全预设"',
    '"Unrestricted"': '"无限制"',
    '"Agent Behavior"': '"智能体行为"',
    '"Artifact Review Policy"': '"产物评审策略"',
    '"Local Permissions"': '"本地权限"',
    '"File Access Rules"': '"文件访问规则"',
    '"Network Access Rules"': '"网络访问规则"',
    '"MCP Tools"': '"MCP 工具"',
    '"Danger Zone"': '"危险区域"',
    '"Delete Project"': '"删除项目"',
    '"Learn more about Unrestricted"': '"了解更多关于"无限制""',
    '"Learn more about "': '"了解更多关于 "',
    '"Rules"': '"规则"',
    '"Show 1 breakdown"': '"显示 1 项明细"',
    '"Terminal Commands"': '"终端命令"',
    '"Commands Outside Sandbox"': '"沙箱外命令"',
    '"Global"': '"全局"',
    '"File Reads"': '"文件读取"',
    '"File Writes"': '"文件写入"',
    '"Read URLs"': '"读取 URL"',
    '"Skills"': '"技能"',
    '"Custom"': '"自定义"',
    '"Hide breakdown"': '"隐藏明细"',
    '"No customizations found for this workspace."': '"当前工作区未找到任何自定义内容。"',
    '"user_global"': '"用户全局"',
    '"Suggestions"': '"建议"',
    '"Navigation"': '"导航"',
    '"Context"': '"上下文"',
    '"Advanced"': '"高级"',
    '"Quota"': '"配额"',
    '"Default Customizations"': '"默认自定义"',
    '"Customize Global Skills"': '"自定义全局技能"',
    '"Custom Agents"': '"自定义智能体"',
    '"MCP Servers"': '"MCP 服务器"',
    '"Actuation Permissions"': '"执行权限"',
    '"Browser Actuation Rules"': '"浏览器执行规则"',
    '"Configure allowed and denied URLs for browser actuation."': '"配置浏览器执行时允许和拒绝的 URL。"',
    '"Edit"': '"编辑"',
    '"Add"': '"添加"',
    '"Delete command"': '"删除命令"',
    '"Remove"': '"移除"',
    '"Cancel"': '"取消"',
    '"Allow List Terminal Commands"': '"允许列表终端命令"',
    '"Deny List Terminal Commands"': '"拒绝列表终端命令"',
    '"Agent Auto-Fix Lints"': '"智能体自动修复 Lint"',
    '"Enable Workspace API"': '"启用 Workspace API"',
    '"Confirm Window Reload"': '"确认窗口重载"',
    '"Enable Demo Mode (Beta)"': '"启用演示模式（Beta）"',
    '"Explain and Fix in Current Conversation"': '"在当前对话中解释并修复"',
    '"Strict Mode"': '"严格模式"',
    '"Agent Non-Workspace File Access"': '"智能体访问工作区外文件"',
    '"Enable Terminal Sandbox"': '"启用终端沙箱"',
    '"Sandbox Allow Network"': '"沙箱允许网络"',
    '"Enable Shell Integration"': '"启用 Shell 集成"',
    '"Terminal Command Auto Execution"': '"终端命令自动执行"',
    '"Agent Host Address"': '"智能体主机地址"',
    '"Review Policy"': '"评审策略"',
    '"Enable Sounds for Agent"': '"为智能体启用提示音"',
    '"Auto-Expand Changes Overview"': '"自动展开变更概览"',
    '"Knowledge"': '"知识库"',
    '"Auto-Open Edited Files"': '"自动打开已编辑文件"',
    '"Open Agent on Reload"': '"重载时打开智能体"',
    '"Suggestions in Editor"': '"编辑器内建议"',
    '"Tab to Jump"': '"Tab 跳转"',
    '"Tab to Import"': '"Tab 导入"',
    '"Tab Speed"': '"Tab 速度"',
    '"Highlight After Accept"': '"接受后高亮"',
    '"Tab Gitignore Access"': '"Tab 访问 .gitignore"',
    '"Browser Javascript Execution Policy"': '"浏览器 JavaScript 执行策略"',
    '"Chrome Binary Path"': '"Chrome 可执行文件路径"',
    '"Browser User Profile Path"': '"浏览器用户配置路径"',
    '"Browser CDP Port"': '"浏览器 CDP 端口"',
    '"Show Selection Actions"': '"显示选区操作"',
    '"Include Jetski Default Customizations"': '"包含 Jetski 默认自定义"',
    '"Prevent Sleep"': '"防止休眠"',
    '"Keep In Menu Bar"': '"保持在菜单栏中"',
    '"Enable Remote Control"': '"启用远程控制"',
    '"Disabled"': '"禁用"',
    '"Request Review"': '"请求评审"',
    '"Always Proceed"': '"始终继续"',
    '"Proceed in Sandbox"': '"在沙箱中继续"',
    '"Fast"': '"快速"',
    '"Slow"': '"慢速"',
    '"Terminal"': '"终端"',
    '"File Access"': '"文件访问"',
    '"Automation"': '"自动化"',
    '"History"': '"历史"',
    '"Sandboxed"': '"沙箱模式"',
    '"Strict"': '"严格模式"',
    '"Enabled"': '"已启用"',
    '"Value:"': '"值："',
    '"When enabled, Agent can interact with Google Workspace through the API to search and read documents."': '"启用后，智能体可以通过 API 与 Google Workspace 交互，搜索并读取文档。"',
    '"Toggle if a confirmation is shown when using the "Reload Window" button."': '"控制使用"重载窗口"按钮时是否显示确认提示。"',
    '"When enabled, "Explain and Fix" actions will continue in the current conversation instead of starting a new one."': '"启用后，"解释并修复"操作会在当前对话中继续，而不是新建对话。"',
    '"When enabled, terminal commands run with sandbox restrictions."': '"启用后，终端命令将在沙箱限制下运行。"',
    '"When enabled, sandboxed commands are allowed to make network requests."': '"启用后，沙箱中的命令可以发起网络请求。"',
    '"When enabled, Agent is given awareness of lint errors created by its edits and may fix them without explicit user prompting."': '"启用后，智能体会感知自身编辑产生的 Lint 错误，并可在无需明确提示的情况下修复。"',
    '"When enabled, the agent will be able to access past conversations to inform its responses."': '"启用后，智能体可以访问历史对话来辅助生成回复。"',
    '"Open files in the background if Agent creates or edits them"': '"当智能体创建或编辑文件时，在后台自动打开这些文件。"',
    '"Manage your plan, credentials, and general preferences."': '"管理你的套餐、凭据和通用偏好设置。"',
    '"When toggled on, Antigravity collects usage data to help Google enhance performance and features."': '"开启后，Antigravity 会收集使用数据，以帮助 Google 改进性能和功能。"',
    '"Receive product updates, tips, and promotions from Google Antigravity via email."': '"通过电子邮件接收来自 Google Antigravity 的产品更新、技巧和推广信息。"',
    '"You can upgrade to a Google AI Ultra plan to receive the highest rate limits."': '"你可以升级到 Google AI Ultra 套餐，以获得最高的速率限制。"',
    '"By using this app, you agree to its"': '"使用此应用即表示你同意其"',
    '"Open Agent panel on window reload"': '"窗口重载时打开智能体面板。"',
    '"Allows the agent to access files outside of your current workspace."': '"允许智能体访问当前工作区之外的文件。"',
    '"Agent cannot modify files outside of the workspace in strict mode."': '"在严格模式下，智能体无法修改工作区之外的文件。"',
    '"Agent will always ask to review in strict mode."': '"在严格模式下，智能体始终会请求评审。"',
    '"Show suggestions when typing in the editor."': '"在编辑器输入时显示建议。"',
    '"Quickly add and update imports with a tab keypress."': '"通过按下 Tab 键快速添加和更新导入。"',
    '"Set the speed of tab suggestions"': '"设置 Tab 建议的显示速度。"',
    '"Highlight newly inserted text after accepting a Tab completion."': '"接受 Tab 补全后高亮新插入的文本。"',
    '"Controls whether the agent can run custom JavaScript to automate complex browser actions."': '"控制智能体是否可以运行自定义 JavaScript 来自动化复杂的浏览器操作。"',
    '"Path to the Chrome/Chromium executable. Leave empty for auto-detection."': '"Chrome/Chromium 可执行文件路径。留空则自动检测。"',
    '"Custom path for the browser user profile directory. Leave empty for default (~/.gemini/antigravity-browser-profile)."': '"浏览器用户配置目录的自定义路径。留空则使用默认值（~/.gemini/antigravity-browser-profile）。"',
    '"Port number for Chrome DevTools Protocol remote debugging. Leave empty for default (9222)."': '"Chrome DevTools Protocol 远程调试端口。留空则使用默认值（9222）。"',
    '"Show "Edit" and "Chat" buttons when selecting text in the editor."': '"在编辑器中选中文本时显示"编辑"和"聊天"按钮。"',
    '"When enabled, the agent will include default customizations, including default skills."': '"启用后，智能体会包含默认自定义内容，包括默认技能。"',
    '"Prevent the computer from sleeping while the app is running."': '"在应用运行期间阻止计算机进入睡眠。"',
    '"The app will be accessible from the menu bar and will keep running in the background when all windows are closed."': '"应用可从菜单栏访问，并会在所有窗口关闭后继续在后台运行。"',
    '"If enabled, you can manage your conversations from the Antigravity website. Please reload the application to apply this setting."': '"启用后，你可以在 Antigravity 网站上管理对话。请重新加载应用以使设置生效。"',
    '"Configure the browser subagent. It requires"': '"配置浏览器子智能体。它需要"',
    '"to be installed. The browser subagent can be invoked by typing /browser in the conversation input box."': '"已安装。可在对话输入框中输入 /browser 来调用浏览器子智能体。"',
    '"No permissions configured."': '"尚未配置任何权限。"',
    '"Controls whether terminal commands require your approval before running."': '"控制终端命令在执行前是否需要你的批准。"',
    '"Restricts agent tools to a secure, isolated local sandbox."': '"将智能体工具限制在安全、隔离的本地沙箱中。"',
    '"Agents run in a secure sandbox that restricts access to external resources outside of your trusted folders."': '"智能体会在安全沙箱中运行，限制其访问受信任文件夹之外的外部资源。"',
    '"Terminal commands always require review and the agent cannot access files outside of its given workspaces."': '"终端命令始终需要评审，且智能体无法访问其指定工作区之外的文件。"',
    '"Execute URLs"': '"执行 URL"',
    '"Allow/deny agent browser actuation access to specific URLs."': '"允许或拒绝智能体对特定 URL 执行浏览器操作。"',
    '"Allow/deny agent read access to specific files or directories."': '"允许或拒绝智能体读取特定文件或目录。"',
    '"Allow/deny agent write access to specific files or directories."': '"允许或拒绝智能体写入特定文件或目录。"',
    '"Allow/deny agent read access to specific URLs or domains."': '"允许或拒绝智能体读取特定 URL 或域名。"',
    '"Allow/deny specific terminal commands."': '"允许或拒绝特定终端命令。"',
    '"Allow/deny agent command execution outside the sandbox."': '"允许或拒绝智能体在沙箱外执行命令。"',
    '"External tools the agent can call via Model Context Protocol."': '"智能体可通过 Model Context Protocol 调用的外部工具。"',
    '"e.g., /path/to/file"': '"例如：/path/to/file"',
    '"e.g., https://example.com"': '"例如：https://example.com"',
    '"e.g., npm test"': '"例如：npm test"',
    '"e.g., curl"': '"例如：curl"',
    '"Enter tool name or server..."': '"输入工具名称或服务器..."',
    '"Inherits from"': '"继承自"',
    '"global settings"': '"全局设置"',
    '". Local permissions have higher priority."': '"。本地权限具有更高优先级。"',
    '"Learn more about"': '"了解更多关于"',
    '"Manage project folders, agent settings, and permissions."': '"管理项目文件夹、智能体设置和权限。"',
    '"Choose a predefined security preset for the agent. This controls terminal auto-execution policy, and file access policy."': '"为智能体选择预定义的安全预设。它会控制终端自动执行策略和文件访问策略。"',
    '"Inherits from global settings. Local permissions have higher priority. Learn more."': '"继承全局设置。本地权限具有更高优先级。了解更多。"',
    '"Inherits from global settings. Local permissions have higher priority. "': '"继承全局设置。本地权限具有更高优先级。"',
    '"Learn more."': '"了解更多。"',
    '"Configure allowed and denied paths for file reads and writes."': '"配置文件读写时允许和拒绝的路径。"',
    '"Configure allowed and denied URLs for reading."': '"配置读取时允许和拒绝的 URL。"',
    '"Configure allowed terminal commands."': '"配置允许的终端命令。"',
    '"Configure allowed commands outside the sandbox."': '"配置沙箱外允许执行的命令。"',
    '"Configure external tools via Model Context Protocol."': '"通过 Model Context Protocol 配置外部工具。"',
    '"The breakdown below shows token usage from customizations like skills, rules, and MCP. If the budget is exceeded, large customizations will be truncated automatically."': '"下方明细显示技能、规则、MCP 等自定义内容的 token 使用情况。如果超出预算，较大的自定义内容会被自动截断。"',
    '"of the customization budget is available."': '"的自定义预算仍可用。"',
    '"The customization budget is available."': '"自定义预算仍可用。"',
    '"Permanently delete this project and all of its conversations."': '"永久删除该项目及其所有对话。"',
    '"Getting started with a Project"': '"项目入门指南"',
    '"Learn more"': '"了解更多"',
    '"Learn More"': '"了解更多"',
    '"Submit"': '"提交"',
    '"Continue"': '"继续"',
    '"Quit"': '"退出"',
    '"Approve"': '"批准"',
    '"Reject"': '"拒绝"',
    '"Allow"': '"允许"',
    '"Deny"': '"拒绝"',
    '"Completed"': '"已完成"',
    '"Task"': '"任务"',
    '"running"': '"运行中"',
    '"Running"': '"运行中"',
    '"completed"': '"已完成"',
    '"Approved"': '"已批准"',
    '"Requested change"': '"请求变更"',
    '"Denied"': '"已拒绝"',
    '"Action Required"': '"需要操作"',
    '"Completed Operations"': '"已完成操作"',
    '"Walkthrough"': '"任务演练"',
    '"Review"': '"评审"',
    '"Wait"': '"等待"',
    'Learn more about ': '了解更多关于 ',
    'Inherits from global settings. Local permissions have higher priority. ': '继承全局设置。本地权限具有更高优先级。',
    'of the customization budget is available.': '的自定义预算仍可用。',
    'Rules\\n(1.6%)': '规则\\n(1.6%)',
    'Show 1 breakdown': '显示 1 项明细',
    'Learn more about Unrestricted': '了解更多关于无限制',
    'Learn more about 无限制': '了解更多关于无限制',
    'Learn more about 无限制"': '了解更多关于无限制"',
    'Inherits from global settings. Local permissions have higher priority. 了解更多.': '继承全局设置。本地权限具有更高优先级。了解更多。',
    '"Check for Updates"': '"检查更新"',
    '"Command Center"': '"命令中心"',
    '"Auxiliary Pane"': '"辅助面板"',
    '"Close Auxiliary Pane"': '"关闭辅助面板"',
    '"Toggle Auxiliary Pane"': '"切换辅助面板"',
    '"Toggle Sidebar"': '"切换侧边栏"',
    '"Minimize"': '"最小化"',
    '"Maximize"': '"最大化"',
    '"Zoom In"': '"放大"',
    '"Zoom Out"': '"缩小"',
    '"Reset Zoom"': '"重置缩放"',
    '"Toggle Fullscreen"': '"全屏"',
    '"Toggle Developer Tools"': '"开发者工具"',
    '"Confirm Window Reload"': '"确认窗口重载"',
    '"Collapse All"': '"全部折叠"',
    '"Close Tab"': '"关闭标签页"',
    '"Close Terminal Tab"': '"关闭终端标签页"',
    '"Open File"': '"打开文件"',
    '"Open Folder"': '"打开文件夹"',
    '"Close Folder"': '"关闭文件夹"',
    '"Close Workspace"': '"关闭工作区"',
    '"All Files"': '"所有文件"',
    '"All Workspaces"': '"所有工作区"',
    '"Configure Branches"': '"配置分支"',
    '"Add Folder"': '"添加文件夹"',
    '"Add recent remote workspace"': '"添加最近远程工作区"',
    '"Clone current workspace into a new independent workspace"': '"将当前工作区克隆为新的独立工作区"',
    '"Project General"': '"项目常规"',
    '"Project Folders"': '"项目文件夹"',
    '"Project Agent"': '"项目智能体"',
    '"Delete Project"': '"删除项目"',
    '"Archive Conversation"': '"归档对话"',
    '"Archive this conversation"': '"归档此对话"',
    '"Create Project"': '"创建项目"',
    '"New Conversation"': '"新建对话"',
    '"Configure workspace-specific permissions, resources, and customizations."': '"配置工作区特定的权限、资源和自定义内容。"',
    '"Agent Settings"': '"智能体设置"',
    '"Agent Behavior"': '"智能体行为"',
    '"Agent Hooks Configuration"': '"智能体钩子配置"',
    '"Agent Script"': '"智能体脚本"',
    '"Agent Script Command Configuration"': '"智能体脚本命令配置"',
    '"Agent State Debug"': '"智能体状态调试"',
    '"Agent Stopped"': '"智能体已停止"',
    '"Agent Loading"': '"智能体加载中"',
    '"Agent terminated due to error"': '"智能体因错误终止"',
    '"This error is likely temporary. You can prompt the model to try again after some time."': '"此错误可能是暂时的。你可以稍后提示模型重试。"',
    '"Agent Non-Workspace File Access"': '"智能体访问工作区外文件"',
    '"Agent Auto-Fix Lints"': '"智能体自动修复 Lint"',
    '"Agent Host Address"': '"智能体主机地址"',
    '"Ask Agent for Help"': '"向智能体求助"',
    '"Ask a quick question without interrupting the main conversation."': '"在不中断主对话的情况下快速提问。"',
    '"Always Ask"': '"始终询问"',
    '"Always Allow"': '"始终允许"',
    '"Always Proceed"': '"始终继续"',
    '"Always run"': '"始终运行"',
    '"Ask every time"': '"每次都询问"',
    '"Allow Once"': '"允许一次"',
    '"Allow once"': '"允许一次"',
    '"Allow in Conversation"': '"在对话中允许"',
    '"Add Comment"': '"添加评论"',
    '"Add Context"': '"添加上下文"',
    '"Add context"': '"添加上下文"',
    '"Add all"': '"添加全部"',
    '"Add to allowlist"': '"加入允许列表"',
    '"Added to allowlist"': '"已加入允许列表"',
    '"Blocked on Your Input"': '"等待你的输入"',
    '"Action Required"': '"需要操作"',
    '"agent requires permission to continue."': '"智能体需要你的许可才能继续。"',
    '"Chat Settings"': '"对话设置"',
    '"Chat Model Metadata"': '"对话模型元数据"',
    '"Verbose agent chat"': '"详细智能体对话"',
    '"Background Task"': '"后台任务"',
    '"Background Tasks"': '"后台任务"',
    '"Background Task Output"': '"后台任务输出"',
    '"Cancel All Tasks"': '"取消所有任务"',
    '"Cancel Task"': '"取消任务"',
    '"Cancel"': '"取消"',
    '"Accept Step"': '"接受步骤"',
    '"Complete verification"': '"完成验证"',
    '"Confirm Undo"': '"确认撤销"',
    '"Confirm Browser Interaction"': '"确认浏览器交互"',
    '"Agent response"': '"智能体回复"',
    '"Analyzed Task Log"': '"已分析任务日志"',
    '"Analyzing Task Log"': '"正在分析任务日志"',
    '"Analyzed content"': '"已分析内容"',
    '"Analyzing content"': '"正在分析内容"',
    '"Cleared Count"': '"清除计数"',
    '"Add Model"': '"添加模型"',
    '"Add Custom Model"': '"添加自定义模型"',
    '"Chat Model Metadata"': '"对话模型元数据"',
    '"Configure AI models and view your quota."': '"配置 AI 模型并查看你的配额。"',
    '"Quota"': '"配额"',
    '"Baseline model quota reached"': '"基础模型配额已用尽"',
    '"Your Plan:"': '"你的套餐："',
    '"Upgrade"': '"升级"',
    '"Add all"': '"添加全部"',
    '"Security Preset"': '"安全预设"',
    '"Agent security mode"': '"智能体安全模式"',
    '"Agent always asks for review."': '"智能体始终请求评审。"',
    '"Agent auto-executes commands matched by an allow list entry."': '"智能体自动执行允许列表中的命令。"',
    '"Agent never asks for review. This maximizes the autonomy of the Agent, but also has the highest risk of the Agent operating over unsafe or injected Artifact content."': '"智能体从不请求评审。这会最大化智能体的自主性，但也具有最高的安全风险。"',
    '"Allow List Terminal Commands"': '"允许列表终端命令"',
    '"Deny List Terminal Commands"': '"拒绝列表终端命令"',
    '"Allow/deny agent browser actuation access to specific URLs."': '"允许或拒绝智能体浏览器操作访问特定 URL。"',
    '"Allow/deny agent read access to specific files or directories."': '"允许或拒绝智能体读取特定文件或目录。"',
    '"Allow/deny agent write access to specific files or directories."': '"允许或拒绝智能体写入特定文件或目录。"',
    '"Allow/deny agent read access to specific URLs or domains."': '"允许或拒绝智能体读取特定 URL 或域名。"',
    '"Allow/deny specific terminal commands."': '"允许或拒绝特定终端命令。"',
    '"Allow/deny agent command execution outside the sandbox."': '"允许或拒绝沙箱外命令执行。"',
    '"Advanced File Access"': '"高级文件访问"',
    '"Advanced Command Access"': '"高级命令访问"',
    '"Advanced Web Access"': '"高级网络访问"',
    '"Advanced Settings"': '"高级设置"',
    '"Commands Outside Sandbox"': '"沙箱外命令"',
    '"Commands the agent can run outside the sandbox in this workspace."': '"智能体可在此工作区沙箱外运行的命令。"',
    '"Configure allowed and denied URLs for reading."': '"配置读取时允许和拒绝的 URL。"',
    '"Configure allowed and denied paths for file reads and writes."': '"配置读写时允许和拒绝的路径。"',
    '"Configure allowed commands outside the sandbox."': '"配置沙箱外允许的命令。"',
    '"Configure allowed terminal commands."': '"配置允许的终端命令。"',
    '"Configure external tools via Model Context Protocol."': '"通过 Model Context Protocol 配置外部工具。"',
    '"Browser Settings"': '"浏览器设置"',
    '"Browser Task"': '"浏览器任务"',
    '"Browser Subagent Viewer"': '"浏览器子智能体查看器"',
    '"Browser Actuation Permissions"': '"浏览器执行权限"',
    '"Browser Actuation Rules"': '"浏览器执行规则"',
    '"Browser Javascript Execution Policy"': '"浏览器 JavaScript 执行策略"',
    '"Browser CDP Port"': '"浏览器 CDP 端口"',
    '"Browser User Profile Path"': '"浏览器用户配置路径"',
    '"Chrome Binary Path"': '"Chrome 可执行文件路径"',
    '"Configure the browser subagent. It requires"': '"配置浏览器子智能体。它需要"',
    '"to be installed. The browser subagent can be invoked by typing /browser in the conversation input box."': '"已安装。可在对话输入框中输入 /browser 来调用浏览器子智能体。"',
    '"Port number for Chrome DevTools Protocol remote debugging. Leave empty for default (9222)."': '"Chrome DevTools Protocol 远程调试端口。留空则使用默认值（9222）。"',
    '"Custom path for the browser user profile directory. Leave empty for default (~/.gemini/antigravity-browser-profile)."': '"浏览器用户配置目录的自定义路径。留空则使用默认值。"',
    '"Path to the Chrome/Chromium executable. Leave empty for auto-detection."': '"Chrome/Chromium 可执行文件路径。留空则自动检测。"',
    '"Controls whether the agent can run custom JavaScript to automate complex browser actions."': '"控制智能体是否可运行自定义 JavaScript 以自动化复杂浏览器操作。"',
    '"Allow remote debugging for this browser instance"': '"允许对此浏览器实例进行远程调试"',
    '"Active Browser page"': '"活跃浏览器页面"',
    '"Active Browser pages"': '"活跃浏览器页面"',
    '"Capture console logs"': '"捕获控制台日志"',
    '"Capture screenshot"': '"捕获截图"',
    '"Appearance"': '"外观"',
    '"Theme"': '"主题"',
    '"Light Theme"': '"浅色主题"',
    '"Dark Theme"': '"深色主题"',
    '"Preset"': '"预设"',
    '"Default Light"': '"默认浅色"',
    '"Default Dark"': '"默认深色"',
    '"Atom One Dark"': '"Atom One Dark"',
    '"Atom One Light"': '"Atom One Light"',
    '"Background"': '"背景"',
    '"Foreground"': '"前景"',
    '"Accent"': '"强调色"',
    '"Active background color of the command center"': '"命令中心活动背景色"',
    '"Active border color of the command center"': '"命令中心活动边框色"',
    '"Active foreground color of the command center"': '"命令中心活动前景色"',
    '"Editor"': '"编辑器"',
    '"Code Search"': '"代码搜索"',
    '"Code Context Items"': '"代码上下文项"',
    '"Show Selection Actions"': '"显示选区操作"',
    '"Suggestions in Editor"': '"编辑器内建议"',
    '"Tab to Jump"': '"Tab 跳转"',
    '"Tab to Import"': '"Tab 导入"',
    '"Tab Speed"': '"Tab 速度"',
    '"Highlight After Accept"': '"接受后高亮"',
    '"Tab Gitignore Access"': '"Tab 访问 .gitignore"',
    '"Suggestions"': '"建议"',
    '"Shortcuts"': '"快捷键"',
    '"Keyboard Shortcuts"': '"键盘快捷键"',
    '"Open Keyboard Shortcuts"': '"打开快捷键"',
    '"Open Conversation Picker"': '"打开对话选择器"',
    '"Open File Search"': '"打开文件搜索"',
    '"Focus Input"': '"聚焦输入框"',
    '"Go Back"': '"返回"',
    '"Go Forward"': '"前进"',
    '"File Picker"': '"文件选择器"',
    '"Select Previous Conversation"': '"上一个对话"',
    '"Select Next Conversation"': '"下一个对话"',
    '"Toggle Model Selector"': '"切换模型选择器"',
    '"Toggle Voice Recording"': '"切换语音录制"',
    '"Find in Pane"': '"在面板中查找"',
    '"Account"': '"账户"',
    '"App Settings"': '"应用设置"',
    '"General"': '"通用"',
    '"Google Drive"': '"谷歌云端硬盘"',
    '"Sign Out"': '"退出登录"',
    '"Email"': '"邮箱"',
    '"Terms of Service"': '"服务条款"',
    '"Manage your plan, credentials, and general preferences."': '"管理你的套餐、凭据和通用偏好设置。"',
    '"Manage application settings."': '"管理应用设置。"',
    '"Prevent Sleep"': '"防止休眠"',
    '"Keep In Menu Bar"': '"保留在菜单栏"',
    '"Enable Remote Control"': '"启用远程控制"',
    '"Enable Telemetry"': '"启用遥测"',
    '"Marketing Emails"': '"营销邮件"',
    '"When toggled on, Antigravity collects usage data to help Google enhance performance and features."': '"开启后，Antigravity 会收集使用数据以帮助 Google 改进产品。"',
    '"Receive product updates, tips, and promotions from Google Antigravity via email."': '"通过邮件接收 Antigravity 产品更新、技巧和推广信息。"',
    '"MCP Tools"': '"MCP 工具"',
    '"MCP Servers"': '"MCP 服务器"',
    '"Add MCP"': '"添加 MCP"',
    '"Add MCP Servers"': '"添加 MCP 服务器"',
    '"Add Handler"': '"添加处理器"',
    '"Add Hook Card"': '"添加钩子卡片"',
    '"External tools the agent can call via Model Context Protocol."': '"智能体可通过 MCP 调用的外部工具。"',
    '"All tools (*)"': '"所有工具 (*)"',
    '"Build With Google Plugins"': '"通过 Google 插件构建"',
    '"Artifact Comments"': '"产物评论"',
    '"Artifact Name"': '"产物名称"',
    '"Artifact Review Policy"': '"产物评审策略"',
    '"Artifact Viewer"': '"产物查看器"',
    '"Artifact not found"': '"未找到产物"',
    '"Artifact URL not found"': '"未找到产物 URL"',
    '"Artifact image"': '"产物图片"',
    '"Provide Feedback"': '"提供反馈"',
    '"Bug Report"': '"Bug 报告"',
    '"An error occurred while submitting your feedback. Please try again."': '"提交反馈时出错，请重试。"',
    '"Attach Antigravity server logs"': '"附加 Antigravity 服务器日志"',
    '"Any relevant information"': '"任何相关信息"',
    '"Any error messages"': '"任何错误信息"',
    '"Actual behavior"': '"实际行为"',
    '"Authentication Required"': '"需要认证"',
    '"Notifications"': '"通知"',
    '"Notification Settings"': '"通知设置"',
    '"Open System Preferences"': '"打开系统偏好设置"',
    '"Knowledge"': '"知识库"',
    '"Skills"': '"技能"',
    '"Active Skills"': '"活跃技能"',
    '"Customize Global Skills"': '"自定义全局技能"',
    '"Scheduled Tasks"': '"计划任务"',
    '"Add Scheduled Task"': '"添加计划任务"',
    '"Add scheduled task"': '"添加计划任务"',
    '"Terminal Commands"': '"终端命令"',
    '"Terminal"': '"终端"',
    '"Enable Terminal Sandbox"': '"启用终端沙箱"',
    '"Sandbox Allow Network"': '"沙箱允许网络"',
    '"Enable Shell Integration"': '"启用 Shell 集成"',
    '"Terminal Command Auto Execution"': '"终端命令自动执行"',
    '"Archived"': '"已归档"',
    '"Select a conversation to start"': '"选择一个对话开始"',
    '"Create a project to get started"': '"创建一个项目开始"',
    '"Custom"': '"自定义"',
    '"Global"': '"全局"',
    '"Add"': '"添加"',
    '"Remove"': '"移除"',
    '"Edit"': '"编辑"',
    '"Submit"': '"提交"',
    '"Continue"': '"继续"',
    '"Approve"': '"批准"',
    '"Reject"': '"拒绝"',
    '"Deny"': '"拒绝"',
    '"Allow"': '"允许"',
    '"Close"': '"关闭"',
    '"History"': '"历史"',
    '"Navigation"': '"导航"',
    '"Context"': '"上下文"',
    '"Advanced"': '"高级"',
    '"Reset to default"': '"恢复默认"',
    '"Reset"': '"重置"',
    '"Clear"': '"清除"',
    '"Apply"': '"应用"',
    '"Copy"': '"复制"',
    '"Copy to clipboard"': '"复制到剪贴板"',
    '"Save"': '"保存"',
    '"Refresh"': '"刷新"',
    '"Loading"': '"加载中"',
    '"Loading..."': '"加载中..."',
    '"No results"': '"无结果"',
    '"No conversations yet"': '"暂无对话"',
    '"No agents running"': '"无运行中的智能体"',
    '"No data available"': '"无可用数据"',
    '"Agent data is not available"': '"智能体数据不可用"',
    '"Disabled"': '"已禁用"',
    '"Enabled"': '"已启用"',
    '"Sandboxed"': '"沙箱模式"',
    '"Strict"': '"严格模式"',
    '"Unrestricted"': '"无限制"',
    '"Fast"': '"快速"',
    '"Slow"': '"慢速"',
    '"Task"': '"任务"',
    '"Completed"': '"已完成"',
    '"Running"': '"运行中"',
    '"completed"': '"已完成"',
    '"running"': '"运行中"',
    '"Failed"': '"失败"',
    '"Error"': '"错误"',
    '"Warning"': '"警告"',
    '"OK"': '"确定"',
    '"Yes"': '"是"',
    '"No"': '"否"',
    '"Dismiss"': '"忽略"',
    '"Retry"': '"重试"',
    '"Try Again"': '"重试"',
    '"View"': '"查看"',
    '"View more"': '"查看更多"',
    '"Show all"': '"显示全部"',
    '"Show less"': '"收起"',
    '"Details"': '"详情"',
    '"Updated"': '"已更新"',
    '"Created"': '"已创建"',
    '"Modified"': '"已修改"',
    '"Sort by"': '"排序方式"',
    '"Filter by"': '"按...筛选"',
    '"Group by"': '"按...分组"',
    '"Alphabetical (A-Z)"': '"字母顺序 (A-Z)"',
    '"Alphabetical (Z-A)"': '"字母顺序 (Z-A)"',
    '"Most recent"': '"最近"',
    '"Oldest"': '"最早"',
    '"Click to copy"': '"点击复制"',
    '"Click to copy URL"': '"点击复制 URL"',
    '"Click to copy full command"': '"点击复制完整命令"',
    '"Click to learn more about sources"': '"点击了解来源详情"',
    '"Copied to clipboard"': '"已复制到剪贴板"',
    '"Danger Zone"': '"危险区域"',
    '"Select all"': '"全选"',
    '"Select none"': '"取消全选"',
    '"Learn More"': '"了解更多"',
    '"Learn more"': '"了解更多"',
    '"Learn more about"': '"了解更多关于"',
    '"of the customization budget is available."': '"自定义预算仍可用。"',
    '"The customization budget is available."': '"自定义预算仍可用。"',
}